# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  sensor:
    - name: "Temperatura"
      state_topic: "sensors/dht11"
      value_template: "{{ value_json.temperature }}"
      unit_of_measurement: "°C"

notify:
  - name: callmebot
    platform: rest
    resource: "https://api.callmebot.com/whatsapp.php"
    method: GET
    data:
      phone: "xxxxxxxxx"
      apikey: "xxxxxxx"
      text: "{{ message }}"
